# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(70, 230, 121, 51))
        self.login.setObjectName("login")
        self.register_2 = QtWidgets.QPushButton(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(230, 230, 111, 51))
        self.register_2.setObjectName("register_2")
        self.user_name = QtWidgets.QLabel(self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(70, 50, 91, 41))
        self.user_name.setObjectName("user_name")
        self.user_passwd = QtWidgets.QLabel(self.centralwidget)
        self.user_passwd.setGeometry(QtCore.QRect(70, 110, 81, 31))
        self.user_passwd.setObjectName("user_passwd")
        self.info_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.info_show.setGeometry(QtCore.QRect(400, 40, 256, 192))
        self.info_show.setObjectName("info_show")
        self.name_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_Edit.setGeometry(QtCore.QRect(130, 50, 151, 31))
        self.name_Edit.setObjectName("name_Edit")
        self.passwd_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwd_Edit.setGeometry(QtCore.QRect(130, 110, 151, 31))
        self.passwd_Edit.setText("")
        self.passwd_Edit.setClearButtonEnabled(True)
        self.passwd_Edit.setObjectName("passwd_Edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WinTest"))
        self.login.setText(_translate("MainWindow", "登录"))
        self.register_2.setText(_translate("MainWindow", "注册"))
        self.user_name.setText(_translate("MainWindow", "账号："))
        self.user_passwd.setText(_translate("MainWindow", "密码："))
